
riddles = {
    "easy": [
            {"question": "What has keys but can't open locks?", "answer": "Piano"},
            {"question": "What gets wetter as it dries?", "answer": "Towel"},
            {"question": "What has to be broken before you can use it?", "answer": "Egg"},
            {"question": "I'm tall when I'm young, and I'm short when I'm old. What am I?", "answer": "Candle"},
            {"question": "What has one eye, but can't see?", "answer": "Needle"},
            {"question": "What has hands but can't clap?", "answer": "Clock"},
            {"question": "What has a neck but no head?", "answer": "Bottle"},
            {"question": "Where does today come before yesterday?", "answer": "Dictionary"},
            {"question": "What belongs to you but others use it more than you do?", "answer": "Your name"},
            {"question": "What has many teeth but can't bite?", "answer": "Comb"},
            {"question": "What runs but never walks?", "answer": "River"},
            {"question": "What comes down but never goes up?", "answer": "Rain"},
            {"question": "What goes up and down but doesn't move?", "answer": "Stairs"},
            {"question": "What has a heart that doesn't beat?", "answer": "Artichoke"},
            {"question": "What is full of holes but still holds water?", "answer": "Sponge"},
            {"question": "What has a face and two hands but no arms or legs?", "answer": "Clock"},
            {"question": "What can you catch but not throw?", "answer": "Cold"},
            {"question": "What kind of band never plays music?", "answer": "Rubber band"},
            {"question": "What gets bigger the more you take away?", "answer": "Hole"},
            {"question": "What's black and white and read all over?", "answer": "Newspaper"},
            {"question": "What has stripes but isn't a tiger?", "answer": "Zebra"},
            {"question": "What begins with T, ends with T, and has T in it?", "answer": "Teapot"},
            {"question": "What has a thumb and four fingers but isn't alive?", "answer": "Glove"},
            {"question": "What month has 28 days?", "answer": "All months"},
            {"question": "What can you keep after giving it to someone?", "answer": "Your word"},
            {"question": "What has a ring but no finger?", "answer": "Telephone"},
            {"question": "What has wheels and flies but is not an airplane?", "answer": "Garbage truck"},
            {"question": "What has ears but cannot hear?", "answer": "Corn"},
            {"question": "What's orange and sounds like a parrot?", "answer": "Carrot"},
            {"question": "What has a bed but never sleeps?", "answer": "River"},
            {"question": "What has roots that nobody sees?", "answer": "Mountain"},
            {"question": "What can travel around the world while staying in a corner?", "answer": "Stamp"},
            {"question": "What has an end but no beginning?", "answer": "Stick"},
            {"question": "What has four fingers and a thumb but isn't alive?", "answer": "Glove"},
            {"question": "What kind of coat is best put on wet?", "answer": "A coat of paint"},
        ],
        
    "normal": [
            {"question": "The more you take, the more you leave behind. What am I?", "answer": "Footsteps"},
            {"question": "What has cities, but no houses; forests, but no trees; and rivers, but no water?", "answer": "Map"},
            {"question": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "The letter M"},
            {"question": "Forward I am heavy, but backward I am not. What am I?", "answer": "Ton"},
            {"question": "What has a head, a tail, is brown, and has no legs?", "answer": "Penny"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "Fire"},
            {"question": "What can fill a room but takes up no space?", "answer": "Light"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but can't go outside. What am I?", "answer": "Keyboard"},
            {"question": "What is seen in the middle of March and April that can't be seen at the beginning or end?", "answer": "The letter R"},
            {"question": "What English word has three consecutive double letters?", "answer": "Bookkeeper"},
            {"question": "What 8-letter word can have a letter taken away and still make a word until only one letter is left?", "answer": "Starting"},
            {"question": "What five-letter word becomes shorter when you add two letters to it?", "answer": "Short"},
            {"question": "If two's company, and three's a crowd, what are four and five?", "answer": "Nine"},
            {"question": "What comes once in a year, twice in a month, four times in a week, and six times in a day?", "answer": "Odd numbers"},
            {"question": "What has six faces but does not wear makeup, has twenty-one eyes but cannot see?", "answer": "Dice"},
            {"question": "I have branches, but no fruit, trunk, or leaves. What am I?", "answer": "Bank"},
            {"question": "What can travel around the world while staying in a corner?", "answer": "Stamp"},
            {"question": "What has a thumb and four fingers but isn't alive?", "answer": "Glove"},
            {"question": "What is black when it's clean and white when it's dirty?", "answer": "Chalkboard"},
            {"question": "What has a neck and a body but no head?", "answer": "Bottle"},
            {"question": "What has a face and two hands but no arms or legs?", "answer": "Clock"},
            {"question": "What can you hold in your right hand but not in your left?", "answer": "Your left hand"},
            {"question": "What has teeth but cannot bite?", "answer": "Comb"},
            {"question": "What has an end but no beginning?", "answer": "Line"},
            {"question": "I'm light as a feather, yet the strongest man can't hold me for much longer than a minute. What am I?", "answer": "Breath"},
            {"question": "What can run but never walks, has a mouth but never talks?", "answer": "River"},
            {"question": "What is easy to get into, but hard to get out of?", "answer": "Trouble"},
            {"question": "I'm tall when I'm young, and I'm short when I'm old. What am I?", "answer": "Candle"},
            {"question": "What can you break, even if you never pick it up or touch it?", "answer": "Promise"},
            {"question": "What has many holes but still holds water?", "answer": "Sponge"},
            {"question": "What has roots that nobody sees?", "answer": "Mountain"},
            {"question": "What is it that lives if it is fed, and dies if you give it a drink?", "answer": "Fire"},
            {"question": "I have a tail and a head but no body. What am I?", "answer": "Coin"},
        ],
        
    "hard": [
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", "answer": "Echo"},
            {"question": "I am not alive, but I grow; I don't have lungs, but I need air; I don't have a mouth, but water kills me. What am I?", "answer": "Fire"},
            {"question": "The person who makes it, sells it. The person who buys it never uses it. The person who uses it never knows they are using it. What is it?", "answer": "Coffin"},
            {"question": "I have branches, but no fruit, trunk, or leaves. What am I?", "answer": "Bank"},
            {"question": "What disappears as soon as you say its name?", "answer": "Silence"},
            {"question": "What has an eye but cannot see?", "answer": "Needle"},
            {"question": "The more you have of it, the less you see. What is it?", "answer": "Darkness"},
            {"question": "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?", "answer": "River"},
            {"question": "If you drop me, I'm sure to crack, but give me a smile and I'll smile back. What am I?", "answer": "Mirror"},
            {"question": "I can be cracked, made, told, and played. What am I?", "answer": "Joke"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can't go outside. What am I?", "answer": "Keyboard"},
            {"question": "What has a neck but no head?", "answer": "Bottle"},
            {"question": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "The letter M"},
            {"question": "What has a bed but never sleeps?", "answer": "River"},
            {"question": "What is always in front of you but can't be seen?", "answer": "Future"},
            {"question": "What begins with T, ends with T, and has T in it?", "answer": "Teapot"},
            {"question": "What can fill a room but takes up no space?", "answer": "Light"},
            {"question": "What gets bigger the more you take away?", "answer": "Hole"},
            {"question": "What is always in front of you but can't be seen?", "answer": "Future"},
            {"question": "I am always hungry; I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "Fire"},
            {"question": "What has teeth but cannot bite?", "answer": "Comb"},
            {"question": "What has a face and two hands but no arms or legs?", "answer": "Clock"},
            {"question": "What can you catch but not throw?", "answer": "Cold"},
            {"question": "I'm tall when I'm young, and I'm short when I'm old. What am I?", "answer": "Candle"},
            {"question": "What begins with T, ends with T, and has T in it?", "answer": "Teapot"},
            {"question": "What goes up but never comes down?", "answer": "Age"},
            {"question": "What has a bottom at the top?", "answer": "Legs"},
            {"question": "What is it that lives if it is fed, and dies if you give it a drink?", "answer": "Fire"},
            {"question": "What has a face and two hands but no arms or legs?", "answer": "Clock"},
            {"question": "What comes once in a year, twice in a month, four times in a week, and six times in a day?", "answer": "Odd numbers"},
    ]
}